"use client";
import { useState } from "react";
import Sidebar from "@/app/components/Sidebar";
import Header from "@/app/components/Header";
import ChatCard from "@/app/components/ChatCard";
import InputBar from "@/app/components/InputBar";

type Message = {
  role: "user" | "assistant";
  content: string;
};

export default function Page() {
  const [messages, setMessages] = useState<Message[]>([
    {
      role: "assistant",
      content:
        "Hello! You can ask a medical question or upload a skin image.",
    },
  ]);

  // ---------------------------
  // TEXT MESSAGE HANDLER
  // ---------------------------
  const sendMessage = async (text: string) => {
    if (!text.trim()) return;

    setMessages((prev) => [...prev, { role: "user", content: text }]);

    try {
      const res = await fetch("http://localhost:5000/api/chat", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ question: text }),
      });

      const data = await res.json();

      setMessages((prev) => [
        ...prev,
        {
          role: "assistant",
          content:
            data.medical_analysis || "No response generated by the system.",
        },
      ]);
    } catch (error) {
      setMessages((prev) => [
        ...prev,
        {
          role: "assistant",
          content: "⚠️ Error connecting to backend.",
        },
      ]);
    }
  };

  // ---------------------------
  // IMAGE UPLOAD HANDLER
  // ---------------------------
  const handleImageUpload = async (file: File) => {
    setMessages((prev) => [
      ...prev,
      {
        role: "user",
        content: `Uploaded ${file.name} skin image for diagnosis.`,
      },
    ]);

    const formData = new FormData();
    formData.append("image", file);

    try {
      const res = await fetch("http://localhost:5000/api/predict-image", {
        method: "POST",
        body: formData,
      });

      const data = await res.json();

      const formattedResponse = `
Predicted Disease: ${data.prediction}
Confidence: ${data.confidence}%

${data.medical_analysis}
      `;

      setMessages((prev) => [
        ...prev,
        {
          role: "assistant",
          content: formattedResponse,
        },
      ]);
    } catch (error) {
      setMessages((prev) => [
        ...prev,
        {
          role: "assistant",
          content: "⚠️ Error processing image.",
        },
      ]);
    }
  };

  return (
    <div className="h-screen flex bg-gradient-to-br from-[#0a0f1e] to-[#1e293b]">
      <Sidebar />

      <main className="flex flex-col flex-1">
        <Header />

        <div className="flex-1 overflow-y-auto p-6 space-y-4">
          {messages.map((msg, i) => (
            <ChatCard key={i} role={msg.role} content={msg.content} />
          ))}
        </div>

        <InputBar onSend={sendMessage} onImageUpload={handleImageUpload} />
      </main>
    </div>
  );
}